CREATE TABLE IF NOT EXISTS chargestation.price_rule (
  id STRING,
  station_id STRING,
  level STRING,
  price STRING,
  time_range STRING
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
NULL DEFINED AS '\\N'
STORED AS TEXTFILE;
